apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat-deployment-nautilus
  name: tomcat-service-nautilus
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32227
  selector:
    app: tomcat-deployment-nautilus
  type: NodePort
