apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-nautilus
  name: pod-nautilus
spec:
  containers:
  - image: httpd:latest
    name: container-nautilus
    volumeMounts:
    - name: pvc-nautilus
      mountPath: /var/www/html
  volumes:
  - name: pvc-nautilus
    persistentVolumeClaim:
      claimName: pvc-nautilus