apiVersion: v1
kind: Service
metadata:
  labels:
    run: pod-nautilus
  name: pod-nautilus
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    run: pod-nautilus
  type: NodePort
