apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-deployment-nautilus
  name: httpd-deployment-nautilus
  namespace: httpd-namespace-nautilus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-deployment-nautilus
  template:
    metadata:
      labels:
        app: httpd-deployment-nautilus
    spec:
      containers:
      - image: httpd:latest
        name: httpd