apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-deployment-nautilus
  name: httpd-service-nautilus
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30004
  selector:
    app: httpd-deployment-nautilus
  type: NodePort
