apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
spec:
  containers:
  - image: busybox:latest
    name: time-check
    env:
    - name: TIME_FREQ
      valueFrom:
         configMapKeyRef:
            name: time-config
            key: TIME_FREQ
    command: ["/bin/sh", "-c"]
    args: ["while true; do date; sleep $TIME_FREQ;done > /opt/dba/time/time-check.log"]
    volumeMounts:
    - mountPath: /opt/dba/time
      name: log-volume
  volumes:
    - name: log-volume
      emptyDir: {}