apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-deployment-datacenter
  name: grafana-deployment-datacenter
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 32000
  selector:
    app: grafana-deployment-datacenter
  type: NodePort