apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: mysqlrootpass
  mysql-database: mysql_db
  mysql-user: mysql_user
  mysql-password: mysql_password
  mysql-host: mysql-service